# Generated by Django 3.2.8 on 2021-10-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211023_0819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
